name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Outsider'

env: 
  DEMO_PLAIN: plain-text
  DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $DEMO_PLAIN
      - run: echo $DEMO_SECRET
      - run: echo "Hello ${{ github.event.inputs.name }}"